apiVersion: v1
kind: Template
metadata:
  name: quay-enterprise
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${QUAY_SERVICE_NAME}
    name: ${QUAY_SERVICE_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${QUAY_SERVICE_NAME}
      deploymentconfig: ${QUAY_SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${QUAY_SERVICE_NAME}
          deploymentconfig: ${QUAY_SERVICE_NAME}
      spec:
        containers:
        - image: 'quay.io/coreos/quay:${QUAY_VERSION}'
          imagePullPolicy: IfNotPresent
          name: quay
          ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /datastorage
            name: data
          - mountPath: /conf/stack
            name: config
          - mountPath: /var/logs
            name: logs
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        imagePullSecrets:
          - name: quay-pull-secret
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${QUAY_SERVICE_NAME}-data
        - name: config
          persistentVolumeClaim:
            claimName: ${QUAY_SERVICE_NAME}-config
        - name: logs
          persistentVolumeClaim:
            claimName: ${QUAY_SERVICE_NAME}-logs
        - name: tmp
          emptyDir: {}
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - quay
          from:
            kind: ImageStreamTag
            name: '${QUAY_SERVICE_NAME}:${QUAY_VERSION}'
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${QUAY_SERVICE_NAME}
    name: ${QUAY_SERVICE_NAME}
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: ${QUAY_SERVICE_NAME}
      deploymentconfig: ${QUAY_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${QUAY_SERVICE_NAME}
    name: ${QUAY_SERVICE_NAME}
  spec:
    port:
      targetPort: 80-tcp
    to:
      kind: Service
      name: ${QUAY_SERVICE_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${QUAY_SERVICE_NAME}-config
    labels:
      app: ${QUAY_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${QUAY_SERVICE_NAME}-data
    labels:
      app: ${QUAY_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${QUAY_SERVICE_NAME}-logs
    labels:
      app: ${QUAY_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
parameters:
- description: The name of the OpenShift Service exposed for Quay Enterprise.
  displayName: Quay Service Name
  name: QUAY_SERVICE_NAME
  required: true
  value: quay
- description: The version of the Quay Enterprise image
  displayName: Quay Version
  name: QUAY_VERSION
  required: true
  value: v2.9.2